version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install -g mocha
  pre_build:
    commands:
      - echo pre-install
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - mocha
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - api/**/*
    - scripts/*
    - test/*
    - server.js
    - appspec.yml
    - package.json
    - package-lock.json